export PATH="$PATH:C:/Users/75897/AppData/Local/Programs/Python/Python39/Scripts"
alias python="winpty python.exe"
export PATH="$PATH:C:/Users/75897/AppData/Local/Programs/Python/Python39/Scripts"
alias python="winpty python.exe"
export PATH="$PATH:C:/Users/75897/AppData/Local/Programs/Python/Python39/Scripts"
alias python="winpty python.exe"
export PATH="$PATH:C:/Users/75897/AppData/Local/Programs/Python/Python39/Scripts"
alias python="winpty python.exe"
